In [13]:
import numpy as np
import pandas as pd

In [14]:
df = pd.read_csv("dataset_Facebook.csv",sep=";")

In [19]:
print("First 5 Rows:")
df.head()

First 5 Rows:

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [21]:
subset1 = df[['Type', 'Category', 'Paid']]

print("\nSubset with selected columns:")
subset1.head()

Subset with selected columns:

     Type  Category  Paid
0   Photo         2   0.0
1  Status         2   0.0
2   Photo         3   0.0
3   Photo         2   1.0
4   Photo         2   0.0

In [20]:
subset2 = df[df['Paid'] == 1]

print("\nSubset where Paid = 1:")
subset2.head()

Subset where Paid = 1:

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
14,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713

In [26]:
# Create first dataframe
data1 = {
    'Post ID': [1, 2, 3, 4],
    'Likes': [100, 200, 300, 400]
}

df1 = pd.DataFrame(data1)

# Create second dataframe
data2 = {
    'Post ID': [1, 2, 3, 4],
    'Comments': [10, 20, 30, 40]
}

In [25]:
df2 = pd.DataFrame(data2)
merged_df = pd.merge(df1, df2, on='Post ID')

print("\nMerged Data:")
merged_df

Merged Data:

   Post ID  Likes  Comments
0        1    100        10
1        2    200        20
2        3    300        30
3        4    400        40

In [28]:
print("\n========== SORT DATA ==========")

# Sort dataset by Total Interactions
sorted_df = df.sort_values(by='Total Interactions',ascending=False)

print("\nData sorted by Total Interactions:")
sorted_df[['Type', 'Total Interactions']].head()

========== SORT DATA ==========

Data sorted by Total Interactions:

      Type  Total Interactions
244  Photo                6334
379  Photo                2177
168  Photo                1974
460  Photo                1873
349  Photo                1806

In [29]:
print("\n========== TRANSPOSE DATA ==========")

transpose_df = df.head().T

print("\nTransposed Data:")
transpose_df

========== TRANSPOSE DATA ==========

Transposed Data:

,0,1,2,3,4
Page total likes,139441,139441,139441,139441,139441
Type,Photo,Status,Photo,Photo,Photo
Category,2,2,3,2,2
Post Month,12,12,12,12,12
Post Weekday,4,3,3,2,2
Post Hour,3,10,3,10,3
Paid,0.0,0.0,0.0,1.0,0.0
Lifetime Post Total Reach,2752,10460,2413,50128,7244
Lifetime Post Total Impressions,5091,19057,4373,87991,13594
Lifetime Engaged Users,178,1457,177,2211,671
Lifetime Post Consumers,109,1361,113,790,410
Lifetime Post Consumptions,159,1674,154,1119,580
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396
comment,4,5,0,58,19
like,79.0,130.0,66.0,1572.0,325.0
share,17.0,29.0,14.0,147.0,49.0
Total Interactions,100,164,80,1777,393

In [30]:
print("\nShape of Dataset:")
print(df.shape)

Shape of Dataset:
(500, 19)

In [32]:
print("\n========== RESHAPED DATA ==========")

reshaped_df = pd.melt(df,id_vars=['Type'],value_vars=['comment', 'like', 'share'])

print("\nReshaped Data:")
reshaped_df.head()

========== RESHAPED DATA ==========

Reshaped Data:

     Type variable  value
0   Photo  comment    4.0
1  Status  comment    5.0
2   Photo  comment    0.0
3   Photo  comment   58.0
4   Photo  comment   19.0